apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-repository-sealed-secret
spec:
  params:
    - name: SEALED_SECRETS_NAMESPACE
      type: string
      description: Namespace where Sealed Secrets is installed.
      default: sealed-secrets
    - name: SECRET_NAME
      type: string
      description: Name of the secret to produce.
    - name: SECRET_NAMESPACE
      type: string
      description: Namespace this secret will belong to.
    - name: GIT_HOST
      type: string
      description: Image registry host (e.g. https://github.com).
      default: "https://github.com"
    - name: GIT_USERNAME
      type: string
      description: Git username.
    - name: GIT_EMAIL
      type: string
      description: Email address associated with this git account.
    - name: GIT_PASSWORD
      type: string
      description: Git password or access token.
  steps:
    - name: generate-sealed-secret
      image: quay.io/pittar/kubeseal-ubi8:0.15
      script: |
        #!/usr/bin/env sh

        tempsecret=$(oc create secret generic $(params.SECRET_NAME) \
            --from-literal="username=$(params.GIT_USERNAME)" \
            --from-literal="password=$(params.GIT_PASSWORD)" \
            --from-literal="email=$(params.GIT_EMAIL)" \
            -n $(params.SECRET_NAMESPACE) \
            -o yaml \
            --dry-run=client)

        tempsecret=$(echo "$tempsecret" | awk '/metadata/{print;print "  annotations:";next}1')
        tempsecret=$(echo "$tempsecret" | awk '/annotations/{print;print "    tekton.dev/git-0: $(params.GIT_HOST))";next}1')

        echo "$tempsecret" | kubeseal --controller-namespace $(params.SEALED_SECRETS_NAMESPACE) > /tmp/$(params.SECRET_NAME).json

        printf "Copy the the following into a file named $(params.SECRET_NAME)-sealed-secret.json and add it to your git repository.\n"
        printf " \n"

        cat /tmp/$(params.SECRET_NAME).json
      resources: {}
