apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: github-sealed-secret
spec:
  params:
    - name: SEALED_SECRETS_NAMESPACE
      type: string
      description: Namespace where Sealed Secrets is installed.
      default: "sealed-secrets"
    - name: SECRET_NAME
      type: string
      description: Name of the secret to produce.
    - name: SECRET_NAMESPACE
      type: string
      description: Namespace this secret will belong to.
    - name: GITHUB_USERNAME
      type: string
      description: GitHub username.
    - name: GITHUB_EMAIL
      type: string
      description: Email address associated with this GitHub account.
    - name: GITHUB_TOKEN
      type: string
      description: GitHub access token.  This is NOT your password.
  steps:
    - name: generate-sealed-secret
      image: quay.io/pittar/kubeseal-ubi8:0.15
      script: |
        #!/usr/bin/env sh

        read -r -d '' TEMP_SECRET << SECRET
        apiVersion: v1
        kind: Secret
        metadata:
          name: $(params.SECRET_NAME)
          namespace: $(params.SECRET_NAMESPACE)
          annotations:
            tekton.dev/git-0: https://github.com # Described below
        type: kubernetes.io/basic-auth
        stringData:
          username: $(params.GITHUB_USERNAME)
          password: $(params.GITHUB_TOKEN)
          email: $(params.GITHUB_EMAIL)
        SECRET

        echo "$TEMP_SECRET" | kubeseal --controller-namespace sealed-secrets > /tmp/$(params.SECRET_NAME).json

        echo "Output Secret"
        cat /tmp/$(params.SECRET_NAME).json
      resources: {}
