apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: quay-sealed-secret
spec:
  params:
    - name: SEALED_SECRETS_NAMESPACE
      type: string
      description: Namespace where Sealed Secrets is installed.
      default: sealed-secrets
    - name: SECRET_NAME
      type: string
      description: Name of the secret to produce.
    - name: SECRET_NAMESPACE
      type: string
      description: Namespace this secret will belong to.
    - name: QUAY_USERNAME
      type: string
      description: Quay username.
    - name: QUAY_EMAIL
      type: string
      description: Email address associated with this Quay account.
    - name: QUAY_PASSWORD
      type: string
      description: Quay password.
  steps:
    - name: generate-sealed-secret
      image: quay.io/pittar/kubeseal-ubi8:0.15
      script: |
        #!/usr/bin/env sh

        TEMP_AUTH="$(params.QUAY_USERNAME):$(params.QUAY_PASSWORD)"
        TEMP_AUTH=`echo $TEMP_AUTH | base64`

        read -r -d '' TEMP_SECRET << SECRET
        apiVersion: v1
        kind: Secret
        metadata:
          annotations:
            tekton.dev/docker-0: https://quay.io
          name: $(params.SECRET_NAME)
          namespace: $(params.SECRET_NAMESPACE)
        type: kubernetes.io/dockerconfigjson
        stringData:
          .dockerconfigjson: "{\"auths\":{\"quay.io\":{\"username\":\"$(params.QUAY_USERNAME)\",\"password\":\"$(params.QUAY_PASSWORD)\",\"email\":\"$(params.QUAY_EMAIL)\",\"auth\":\"$TEMP_AUTH\"}}}"
        SECRET

        echo "$TEMP_SECRET" | kubeseal --controller-namespace $(params.SEALED_SECRETS_NAMESPACE) > /tmp/$(params.SECRET_NAME).json

        echo "Output Secret"
        cat /tmp/$(params.SECRET_NAME).json
      resources: {}
