apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: admin-pipelines

bases:
  - ../../../../base/02-rbac/openshift-gitops
  - tasks
  - pipelines

resources:
  - namespace.yaml
