apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: generate-git-repository-sealed-secret
spec:
  params:
    - name: SEALED_SECRETS_NAMESPACE
      type: string
      description: Namespace where Sealed Secrets is installed.
      default: sealed-secrets
    - name: SECRET_NAME
      type: string
      description: Name of the secret to produce.
    - name: SECRET_NAMESPACE
      type: string
      description: Namespace this secret will belong to.
    - name: GIT_HOST
      type: string
      description: Image registry host (e.g. https://github.com).
      default: "https://github.com"
    - name: GIT_USERNAME
      type: string
      description: Git username.
    - name: GIT_EMAIL
      type: string
      description: Email address associated with this git account.
    - name: GIT_PASSWORD
      type: string
      description: Git password or access token.
  tasks:
    - name: generate-sealed-secret
      taskRef:
        name: git-repository-sealed-secret
        kind: Task
      params:
        - name: SEALED_SECRETS_NAMESPACE
          value: $(params.SEALED_SECRETS_NAMESPACE)
        - name: SECRET_NAME
          value: $(params.SECRET_NAME)
        - name: SECRET_NAMESPACE
          value: $(params.SECRET_NAMESPACE)
        - name: GIT_HOST
          value: $(params.GIT_HOST)
        - name: GIT_USERNAME
          value: $(params.GIT_USERNAME)
        - name: GIT_EMAIL
          value: $(params.GIT_EMAIL)
        - name: GIT_PASSWORD
          value: $(params.GIT_PASSWORD)
