apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: contoso-devops-pipeline
spec:
  params:
    - name: SEALED_SECRETS_NAMESPACE
      type: string
      description: Namespace where Sealed Secrets is installed.
      default: "sealed-secrets"
    - name: SECRET_NAME
      type: string
      description: Name of the secret to produce.
    - name: SECRET_NAMESPACE
      type: string
      description: Namespace this secret will belong to.
    - name: GITHUB_USERNAME
      type: string
      description: GitHub username.
    - name: GITHUB_EMAIL
      type: string
      description: Email address associated with this GitHub account.
    - name: GITHUB_TOKEN
      type: string
      description: GitHub access token.  This is NOT your password.
  tasks:
    - name: generate-sealed-secret
      taskRef:
        name: github-sealed-secret
        kind: Task
      params:
        - name: SEALED_SECRETS_NAMESPACE
          value: $(params.SEALED_SECRETS_NAMESPACE)
        - name: SECRET_NAME
          value: $(params.SECRET_NAME)
        - name: SECRET_NAMESPACE
          value: $(params.SECRET_NAMESPACE)
        - name: GITHUB_USERNAME
          value: $(params.GITHUB_USERNAME)
        - name: GITHUB_EMAIL
          value: $(params.GITHUB_EMAIL)
        - name: GITHUB_TOKEN
          value: $(params.GITHUB_TOKEN)
