apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: image-registry-new-sealed-secret
spec:
  params:
    - name: SEALED_SECRETS_NAMESPACE
      type: string
      description: Namespace where Sealed Secrets is installed.
      default: sealed-secrets
    - name: SECRET_NAME
      type: string
      description: Name of the secret to produce.
    - name: SECRET_NAMESPACE
      type: string
      description: Namespace this secret will belong to.
    - name: REGISTRY_HOST
      type: string
      description: Image registry host (e.g. https://quay.io).
      default: "https://quay.io"
    - name: REGISTRY_USERNAME
      type: string
      description: Registry username.
    - name: REGISTRY_EMAIL
      type: string
      description: Email address associated with this Registry account.
    - name: REGISTRY_PASSWORD
      type: string
      description: Registry password.
  tasks:
    - name: generate-sealed-secret
      taskRef:
        name: image-registry-sealed-secret
        kind: Task
      params:
        - name: SEALED_SECRETS_NAMESPACE
          value: $(params.SEALED_SECRETS_NAMESPACE)
        - name: SECRET_NAME
          value: $(params.SECRET_NAME)
        - name: SECRET_NAMESPACE
          value: $(params.SECRET_NAMESPACE)
        - name: REGISTRY_HOST
          value: $(params.REGISTRY_HOST)
        - name: REGISTRY_USERNAME
          value: $(params.REGISTRY_USERNAME)
        - name: REGISTRY_EMAIL
          value: $(params.REGISTRY_EMAIL)
        - name: REGISTRY_PASSWORD
          value: $(params.REGISTRY_PASSWORD)
