apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quay-new-sealed-secret
spec:
  params:
    - name: SEALED_SECRETS_NAMESPACE
      type: string
      description: Namespace where Sealed Secrets is installed.
      default: sealed-secrets
    - name: SECRET_NAME
      type: string
      description: Name of the secret to produce.
    - name: SECRET_NAMESPACE
      type: string
      description: Namespace this secret will belong to.
    - name: QUAY_USERNAME
      type: string
      description: Quay username.
    - name: QUAY_EMAIL
      type: string
      description: Email address associated with this Quay account.
    - name: QUAY_PASSWORD
      type: string
      description: Quay password.
  tasks:
    - name: generate-sealed-secret
      taskRef:
        name: quay-sealed-secret
        kind: Task
      params:
        - name: SEALED_SECRETS_NAMESPACE
          value: $(params.SEALED_SECRETS_NAMESPACE)
        - name: SECRET_NAME
          value: $(params.SECRET_NAME)
        - name: SECRET_NAMESPACE
          value: $(params.SECRET_NAMESPACE)
        - name: QUAY_USERNAME
          value: $(params.QUAY_USERNAME)
        - name: QUAY_EMAIL
          value: $(params.QUAY_EMAIL)
        - name: QUAY_PASSWORD
          value: $(params.QUAY_PASSWORD)
